require 'rake/testtask'

desc 'Run test-unit'
Rake::TestTask.new do |t|
  t.libs << __dir__
  t.libs << "test"
  t.test_files = Dir["test/**/test_*.rb"].sort
  t.verbose = true
end
task :default => :test
