# frozen_string_literal: true
source "https://rubygems.org"

gem 'sinatra'

group :development do
  gem 'awesome_print'
end

group :test do
  gem 'rspec'
end

group :development, :test do
  gem 'pry'
end

